### ISSUE TITLE
Datetime object 'year' attribute

### ISSUE THREAD

**Issue by marcosValle** [gartnera/tinyctf-platform#1]
This is what I get when I run server.py

> Traceback (most recent call last):
>   File "server.py", line 530, in <module>
>     config['startTime'] = dateparser.parse(config['startTime'])
>   File "/usr/local/lib/python2.7/dist-packages/dateparser/conf.py", line 80, in wrapper
>     return f(_args, *_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/dateparser/**init**.py", line 40, in parse
>     data = parser.get_date_data(date_string, date_formats)
>   File "/usr/local/lib/python2.7/dist-packages/dateparser/date.py", line 343, in get_date_data
>     language, date_string, date_formats, settings=self._settings)
>   File "/usr/local/lib/python2.7/dist-packages/dateparser/date.py", line 161, in parse
>     return instance._parse()
>   File "/usr/local/lib/python2.7/dist-packages/dateparser/date.py", line 171, in _parse
>     date_obj = parser()
>   File "/usr/local/lib/python2.7/dist-packages/dateparser/date.py", line 189, in _try_dateutil_parser
>     self._get_translated_date(), settings=self._settings)
>   File "/usr/local/lib/python2.7/dist-packages/dateparser/conf.py", line 80, in wrapper
>     return f(_args, *_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/dateparser/date_parser.py", line 180, in parse
>     date_obj, period = dateutil_parse(date_string, settings=settings)
>   File "/usr/local/lib/python2.7/dist-packages/dateparser/date_parser.py", line 163, in dateutil_parse
>     return new_parser().parse(date_string, settings=settings, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/dateparser/date_parser.py", line 40, in parse
>     new_date = self._populate(res, default, settings=settings)
>   File "/usr/local/lib/python2.7/dist-packages/dateparser/date_parser.py", line 68, in _populate
>     value = getattr(res, field)
> AttributeError: 'tuple' object has no attribute 'year'

It seems to me this issue is related to dateutil version. In fact, I solved this issue by running 

`$ pip install python-dateutil==1.5`

If that is so, you might want to add this observation to README.md while the source is not updated.

**Comment by marcosValle** [comment]
Thanks! :+1:
